services:
  db:
    image: mysql:8.0
    restart: on-failure
    env_file:
      - app/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  web:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - app/.env
    volumes:
      - ./app:/app  # Ensure your app directory is mounted properly
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  db_data:
